name: Mirror

on:
  push:
  repository_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  client-wasm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push image
      if: github.event_name == 'push'
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        repository: acblog/wasm
        tags: latest
        dockerfile: ./docker/client/wasm/Dockerfile
  client-wasmhost:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push image
      if: github.event_name == 'push'
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        repository: acblog/wasm-host
        tags: latest
        dockerfile: ./docker/client/wasm-host/Dockerfile
  server-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push image
      if: github.event_name == 'push'
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        repository: acblog/api
        tags: latest
        dockerfile: ./docker/server/api/Dockerfile